### ISSUE TITLE
Chess: Add Drag and Drop capabilities

### ISSUE THREAD

**Issue by flamecoals** [freeboardgame/FreeBoardGame.org#122]

**Comment by flamecoals** [comment]
See boardgame.io example made by yours truly

**Comment by jasonharrison** [comment]
https://github.com/nicolodavis/boardgame.io/commit/230da1ea27c40c502ef0e15e8b75bff1d60e4ceb

**Comment by jasonharrison** [comment]
@flamecoals You were working on this a while ago, and I think you even got it working -- what's the progress?  If it isn't finished, can you commit what you have and I'll try?
