### ISSUE TITLE
Use SSRHelper.isSSR() in App.tsx?

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgame/FreeBoardGame.org#293]
https://github.com/freeboardgame/FreeBoardGame.org/blob/88530a425d3216ed09cd937fd91ae5aeaba4d92a/src/App/App.tsx#L69 

Can we use SSRHelper.isSSR() instead?

https://github.com/freeboardgame/FreeBoardGame.org/blob/ea2d1cdfd0ef1b7b4e2da1018e93c5b9c5ac6038/src/App/Helpers/SSRHelper.ts#L1-L6

What is the purpose of
```javascript 
typeof document !== 'undefined'
```
?

**Comment by flamecoals** [comment]
I think so, I probably just pasted and code this code from stackoverflow
