### ISSUE TITLE
Pressing back button from game lobby waiting page creates a new room

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgame/FreeBoardGame.org#374]
Pressing back button from game lobby waiting page creates a new room (instead of returns to the game list)

On Android using Chrome

**Comment by flamecoals** [comment]
The easier way to fix this is to use ReplaceState from the game info:
https://stackoverflow.com/questions/20937280/how-to-change-url-without-changing-browser-history

Instead of being a normal link
