### ISSUE TITLE
Create lobby/nickname registration across the app.

### ISSUE THREAD

**Issue by flamecoals** [freeboardgame/FreeBoardGame.org#62]
Some requirements:
- User should be prompted for a nickname if it is their first time using that device.
- Users should know when each other is connected and ready to play.
- The game should automatically start after everybody is ready.
- We should store the logs of games for each player, so in the future we can do ranking and etc.
- Allow users to backup their account/game history with an email (nice to have).

**Comment by jasonharrison** [comment]
What is the current plan for this?  iirc we were going to do this more generally in the BGIO repo rather than FBG, right?

**Comment by flamecoals** [comment]
Yes, the latest is that we would create a design doc for BGIO. But I didnt start yet

**Comment by jasonharrison** [comment]
BGIO issue https://github.com/nicolodavis/boardgame.io/issues/354

Design doc https://docs.google.com/document/d/1K0xDlyS_80WJic7GfNobl-SujfC8_LiB55-JJnAawNM/edit
